Class {
	#name : 'TableQueryRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-Table-Query-Namespace',
	#package : 'Rudesheim-Table-Query',
	#tag : 'Namespace'
}

{ #category : 'namespace' }
TableQueryRudesheim class >> Backend [
	^ BackendTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> BinaryExpression [
	^ BinaryExpressionTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> ConstantExpression [
	^ ConstantExpressionTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> EvaluatorForExpression [
	^ EvaluatorForExpressionTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> Expression [
	^ ExpressionTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> ExpressionCapturingStatement [
	^ ExpressionCapturingStatementTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> FieldExpression [
	^ FieldExpressionTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> Iterator [
	^ IteratorTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> MessageExpression [
	^ MessageExpressionTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> ParameterCapture [
	^ ParameterCaptureTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> ParameterExpression [
	^ ParameterExpressionTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> ProjectionExpression [
	^ ProjectionExpressionTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> Query [
	^ QueryTableQueryRudesheim.
]

{ #category : 'namespace' }
TableQueryRudesheim class >> QuerySource [
	^ QuerySourceTableQueryRudesheim.
]
